# -*- coding: utf-8 -*-
"""AAI_final_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZhZPM5e_ebYGNTSAfd-iqmz79d2KtRj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, accuracy_score

dataset= pd.read_csv ("card_transdata_son.csv")

print("Size of Dataset:", dataset.shape)
print("-------------------------------------------------------------------------")
dataset.head(10)

print(dataset.info())

print(dataset.isnull().sum())

print("balance test:\n", dataset['fraud'].value_counts())

data_0 = dataset[dataset.fraud == 0]
data_1 = dataset[dataset.fraud == 1]

data_0_downsampled = resample(data_0, replace=False, n_samples=len(data_1),random_state=42 )

balanced_dataset = pd.concat([data_0_downsampled, data_1])

balanced_dataset = balanced_dataset.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_dataset['fraud'].value_counts())

X = balanced_dataset.drop("fraud", axis=1)
Y = balanced_dataset["fraud"]

print(X.shape)

column_trans = make_column_transformer(
    (StandardScaler(), ['distance_from_home', 'distance_from_last_transaction', 'ratio_to_median_purchase_price']),
    remainder='passthrough'
)

X = column_trans.fit_transform(X)

print(X.shape)

X_train, X_test, Y_train,Y_test = train_test_split( X,Y, test_size= 0.3 , random_state=42)

model_entropy= DecisionTreeClassifier(criterion = 'entropy', random_state=42)

model_gini = DecisionTreeClassifier ( criterion = 'gini', max_depth= 5, random_state=42)

model_gini.fit(X_train, Y_train)
predicts= model_gini.predict(X_test)


print("Accuracy score with test set = ", model_gini.score(X_test, Y_test))
print("Accuracy score with train set = ", model_gini.score(X_train, Y_train))

model_entropy.fit(X_train, Y_train)

predicts= model_entropy.predict(X_test)



print("Accuracy score with test set = ", model_entropy.score(X_test, Y_test))

from sklearn.metrics import confusion_matrix, accuracy_score

confusion_matrix(y_true=Y_test, y_pred= predicts)

print("Success : " , accuracy_score ( y_true= Y_test, y_pred= predicts))

feature_names = [
    'distance_from_home',
    'distance_from_last_transaction',
    'ratio_to_median_purchase_price',


    'used_chip',
    'used_pin_number',
    'repeat_retailer',
    'online_order'
]

gini_tree_text = tree.export_text(model_gini, feature_names=feature_names)
print("Gini Kriterli Karar Ağacı Yapısı:")
print(gini_tree_text)

plt.figure(figsize=(20, 10))
plot_tree(model_gini,
          feature_names=feature_names,
          class_names=['Not Fraud', 'Fraud'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title("Gini Kriterli Karar Ağacı (max_depth=3)")
plt.show()